sudo: required # 관리자 권한 부여

language: generic # 언어(플랫폼) 선택

services:
	- docker # 도커 환경 구성

before_install: # 스크립트를 실행하기 전에, 환경 구성
	- docker build -t jw0401/docker-fullstack -f ./frontend/Dockerfile.dev ./frontend # 프론트엔드 도커 빌드

script: # 스크립트 실행
	- docker run -e CI=true jw0401/docker-fullstack npm run test -- --coverage # 도커 테스트 실행
		# -e CI=true : Travis CI에서 필수로 작성해야 하는 내용
		# -- --coverage : 테스트한 내용을 상세하게 확인할 수 있는 옵션

after_success: # 테스트 성공 후에, 실행할 내용
	- docker build -t jw0401/docker-frontend ./frontend # 프론트엔드 도커 빌드
  - docker build -t jw0401/docker-backend ./backend   # 백엔드 도커 빌드
  - docker build -t jw0401/docker-nginx ./nginx       # nginx 도커 빌드

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jw0401/docker-frontend
  - docker push jw0401/docker-backend
  - docker push jw0401/docker-nginx 